server:
  port: 1000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: api-gateway
          uri: lb://api-gateway
          predicates:
            - Path=/

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: testing-service
          uri: lb://testing-service
          predicates:
            - Path=/testing/**
          filters:
            - AuthenticationFilter
        
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter
        
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
